### ISSUE TITLE
Command line builder for FCCs

### ISSUE THREAD

**Issue by bostrt** [coreos/butane#129]
*NOTE*: This is partially duplicated work now that I've learned about fcct local files: https://github.com/coreos/fedora-coreos-docs/issues/163

I've been working on a command line builder for FCCs, called `fccb`. Source is here: <https://github.com/bostrt/fccb>. My use case is for building FCCs from files that are in Git that I'd rather keep there for various reasons, including:

- Better version tracking and potentially easier merges then keeping in an FCC Yaml 
- Easier to use linting tools on content *outside* of YAML (e.g. https://github.com/koalaman/shellcheck) 
- Syntax highlighters function better when code isn't embedded in YAML

A side use-case is that command line interaction is sometimes more fun than editing YAML directly.

I'm curious if anyone else in the Fedora CoreOS community might find `fccb` useful and if so, do you think a standalone tool is appropriate or if I should submit a PR to `fcct`?

Below are some examples that might better explain what this tool does exactly. BTW, Its output is FCC that can be piped directly into `fcct`. I didn't go directly to Ignition configs since `fcct` handles that already. 

```
$ fccb add file test.fcc mymotd.txt -p /etc/motd | fcct -p # Add motd and instantly transpile
$ fccb add unit test.fcc -f test.service -d test.service.d/ # Add Systemd service unit and some drop-ins
$ fccb add user test.fcc -n bostrt -G floppy -s /bin/ksh # Add user in floppy and uses KSH
...
```

**Comment by bgilbert** [comment]
I think this isn't the direction we'd want to go for Butane, since it could encourage folks to keep their canonical configuration in their bash history (or a random shell script or Makefile) rather than in a proper config.  As you say, `local` files and `storage.trees` entries should help with your use case.

I'll close this out.  Thanks for the pointer!
