### ISSUE TITLE
How to use local with the (Docker) container?

### ISSUE THREAD

**Issue by rugk** [coreos/butane#139]
In order to use `local` you need to use `-d`, but in Docker/Podman, you of course also need to mount the source dir in there somehow.

How/At which path do you need to mount it?
I've tried this: `podman run -v ./coreos-config:/usr/local/bin/coreos-config -i --rm quay.io/coreos/fcct:release --pretty --strict -d coreos-config/files ·[…]`

…, but it did not really work.

**Comment by rugk** [comment]
Ah okay, seems to be the root dir (`/`) actually:
`podman run -v ./coreos-config:/coreos-config -i --rm quay.io/coreos/fcct:release --pretty --strict -d coreos-config/files […]`

However, on Fedora this causes SeLinux erros, and despite running all this, podman does not seem to be able to access the files:
```
ausearch -c 'fcct' --raw | audit2allow -M my-fcct
semodule -X 300 -i my-fcct.p
/sbin/restorecon -v ./coreos-config/files/scripts/userinit.sh

**Comment by bgilbert** [comment]
This works for me:

```
podman run -v ./files:/files -i --rm quay.io/coreos/fcct:release --pretty --strict -d /files < local.fcc
```

If you're seeing SELinux issues, you could try running podman with `--privileged`.

**Comment by bgilbert** [comment]
There doesn't seem to be anything further to fix here, so I'll close this out.
