### ISSUE TITLE
Rename FCCT

### ISSUE THREAD

**Issue by bgilbert** [coreos/butane#167]
With the addition of the `rhcos` variant (https://github.com/coreos/fcct/pull/164), FCCT is no longer specific to FCOS.

**Comment by LorbusChris** [comment]
I think we should do it - and along with it refer to the family of CoreOS Configs as either `CC` or since that term is overloaded, maybe even better something like `COSC`.

**Comment by bgilbert** [comment]
I was thinking we'd continue to refer to the configs by `variant` - so we'd have FCC, RCC, etc.  Open to ideas though.

**Comment by miabbott** [comment]
How about Ignition Config Transpiler (`ict`)?  We can avoid additional overloading `coreos` this way.

**Comment by bgilbert** [comment]
@miabbott Doesn't that imply that we're consuming Ignition configs rather than producing them?

In any event, we'll still need a name for the input format.  I agree "CoreOS Config" isn't great, but I guess the alternative is a new arbitrary name.

**Comment by miabbott** [comment]
> @miabbott Doesn't that imply that we're consuming Ignition configs rather than producing them?
> 
> In any event, we'll still need a name for the input format. I agree "CoreOS Config" isn't great, but I guess the alternative is a new arbitrary name.

I dunno...I suppose it depends on how you parse the name. I read it as "this tool produces Ignition configs".  It seems either interpretation could be correct...so maybe an arbitrary name would be better.

**Comment by bgilbert** [comment]
See related discussion at https://github.com/kubernetes-sigs/cluster-api/pull/4172#discussion_r578626922.

**Comment by ashcrow** [comment]
Maybe we should discuss a name for the format first. If we can find a replacement for "Fedora CoreOS Config" that possibly follows the ignition theme that may help us move this forward. I'm not well versed in engine ignition stages but I'm sure the Internet can enlighten us :smile:.

**Comment by Okeanos** [comment]
I have no stakes in this but would like to point out that a brew formula for this project (aptly named [fcct](https://formulae.brew.sh/formula/fcct)) exists and can, in the end, hopefully be renamed without conflicts.

**Comment by LorbusChris** [comment]
> @miabbott Doesn't that imply that we're consuming Ignition configs rather than producing them?
> 
> In any event, we'll still need a name for the input format. I agree "CoreOS Config" isn't great, but I guess the alternative is a new arbitrary name.

I'm +1 for Ignition Config Transpiler!

FWIW when I google "c transpiler" the very first link is to https://github.com/dbohdan/compilers-targeting-c

**Comment by bgilbert** [comment]
I think it's worth exploring along the lines of @ashcrow's comment.  A rename to "ICT" doesn't address the naming of the individual distro configs, and if we eventually get more uptake with other distros, our current naming scheme probably won't work.  "Debian Config" would be too generic, "Debian CoreOS Config" too confusing.  Already the situation is messy enough with FCCs and RCCs and maybe "OCCs" (OpenShift CoreOS Configs?).

If we can find a new tool name _X_, then we could have X Configs (an umbrella term for YAML documents consumed by X; we don't have such a term right now) and maybe FCOS X Configs and OpenShift X Configs.

**Comment by travier** [comment]
I was thinking of something fuel related, as in FCCs/Configs are the fuel needed for Ignition?

**Comment by LorbusChris** [comment]
also bikeshedding a bit:
- Oxy Config (FOxy and RHOxy) (add a spark and you have ignition)
- Core Config
- Coreositizer / Coreosity

**Comment by miabbott** [comment]
> I was thinking of something fuel related, as in FCCs/Configs are the fuel needed for Ignition?

How about `Butane`?

**Comment by jlebon** [comment]
How about just keeping it as "fcct" but changing what it stands for? (I joked once the letters reminded me of [focaccia](https://en.wikipedia.org/wiki/Focaccia)). Or we can pull an OKD and just say it doesn't stand for anything. :wink:

**Comment by LorbusChris** [comment]
"Fairly Capable Config Transpiler" or "FCCT Compute(r) Config Transpiler"

**Comment by ashcrow** [comment]
I also like the idea of having it recursive :+1:. 

- "FCCT Combined Config Transpiler"
- "FCCT Compose & Config Transpiler"
- etc...

**Comment by control-d** [comment]
> > @miabbott Doesn't that imply that we're consuming Ignition configs rather than producing them?
> > In any event, we'll still need a name for the input format. I agree "CoreOS Config" isn't great, but I guess the alternative is a new arbitrary name.
> 
> I dunno...I suppose it depends on how you parse the name. I read it as "this tool produces Ignition configs". It seems either interpretation could be correct...so maybe an arbitrary name would be better.

Will that be confusing if the tool defaults (for some variants) to producing MachineConfigs instead?  

I like CoreOS Config Transpiler (cct), though I can see how that might be a problem if ignition makes it's way into other distros.  I imagine that Ignition Config Transpiler will make a lot of sense in those situations where ignition is standalone.

**Comment by sinnykumari** [comment]
How about:

MCT (Machine Config Transpiler)
or,
MOSCT (Machine & OS Config Transpiler)

It covers ignition configs as well any distro/product specific configs that applies to configure system.

**Comment by ashcrow** [comment]
MCT sounds good -- but it could be confusing for folks using OCP since the end result is an Ignition file rather than an OCP Machine Config.

**Comment by sinnykumari** [comment]
> MCT sounds good -- but it could be confusing for folks using OCP

Yeah, that's why I also proposed MOSCT :laughing:

**Comment by cgwalters** [comment]
If we add this to `oc` it may make sense to roll in with https://github.com/openshift/oc/pull/628

**Comment by bgilbert** [comment]
@cgwalters We've discussed vendoring FCCT into `oc` but we're not pursuing that at the present time.  In any event, the codebase will still handle OSes beyond Fedora CoreOS, so it wouldn't save us from a renaming.

**Comment by ashcrow** [comment]
binary || library are there any objections for us taking the proposed names and giving folks a little time to vote? I'd like us to come to a conclusion sooner rather than later if possible.

**Comment by cgwalters** [comment]
If we choose the library path there isn't any renaming, or at least not immediately; the functionality for rhcos and MachineConfigs in particular would mainly be exposed as part of `oc`.

**Comment by ashcrow** [comment]
> If we choose the library path there isn't any renaming, or at least not immediately; the functionality for rhcos and MachineConfigs in particular would mainly be exposed as part of `oc`.

That is true. In that case why don't we have someone chose an option and run with it. We have some good ones and by making a choice we can close this issue out and signal the functionality isn't tied to Fedora directly.

**Comment by bgilbert** [comment]
This is on my plate in the next day or so.
