### ISSUE TITLE
/bin/fcct: /lib64/libc.so.6: version `GLIBC_2.32' not found  error

### ISSUE THREAD

**Issue by turguns** [coreos/butane#221]
Hi ,
Getting the following error:
# ../../bin/fcct --version
../../bin/fcct: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by ../../bin/fcct

https://access.redhat.com/solutions/1285263
RHEL 7 maximum supported version is 2.17 (https://access.redhat.com/solutions/1285263)

How can I compile from source code  for RHEL 7? Can you share the procedure?
Regards,

**Comment by jlebon** [comment]
The preferred way to use `fcct` is as a container. See https://coreos.github.io/fcct/getting-started/#getting-fcct. RHEL7's `podman` should be able to pull and run it.

Out of curiosity, did you get a reference to running `fcct` directly from RHEL documentation?

**Comment by bgilbert** [comment]
I'll go ahead and close this out.
