### ISSUE TITLE
New release has changed its gpg key without mentioning anywhere

### ISSUE THREAD

**Issue by aminvakil** [coreos/butane#245]
Signature has been changed in 0.12.0 again and this has not been mentioned in release again and I'm not sure if this is my problem again and if I should I open a new issue again :)

I used to verify package with `963A2BEB02009608FE67EA4249FD77499570FF31` (Fedora 33), now it should be verified with `8C5BA6990BDB26E19F2A1A801161AE6945719A39` (Fedora 34).

This has happened and reported on https://github.com/coreos/butane/issues/173 before.

**Comment by bgilbert** [comment]
Yes, you're correct.  :disappointed:  Thanks for reporting this again.  I've updated the release notes and I'll start another discussion about https://github.com/coreos/butane/issues/174.
