### ISSUE TITLE
print --help to stdout

### ISSUE THREAD

**Issue by eriksjolund** [coreos/butane#267]
I would like to be able to use the command
```
$ butane --help | grep files-dir
```
instead of 

```
$ butane --help 2>&1 | grep files-dir
  -d, --files-dir string   allow embedding local files from this directory
$ 
```

I think  that most Linux command-line tools  print `--help` to stdout.
Currently __butane__ prints `--help`to stderr.

**Comment by bgilbert** [comment]
We're using the default behavior of [clap](https://docs.rs/clap/2.33.3/clap/), our argument parser.  To stay consistent with the rest of the ecosystem, I expect we'll continue to do so.  If you'd like, you could file a [clap bug](https://github.com/clap-rs/clap/issues/new/choose).

**Comment by eriksjolund** [comment]
I found this example from clap-rs where they have an assert that `--help` should give a non-empty output on stdout:
https://github.com/clap-rs/clap/blob/286fda0b4a243e19d73a254d2dc17c794f4320e5/tests/examples.rs#L47

Then  I found
https://github.com/coreos/butane/blob/339c96e5808144e4c081631134195726eb3c1c0e/internal/main.go#L70
and this 
https://github.com/coreos/butane/blob/339c96e5808144e4c081631134195726eb3c1c0e/internal/main.go#L56

It seems the stderr is set in the Butane code.
(Disclaimer: I don't know rust, so it's a bit of guessing)

**Comment by bgilbert** [comment]
Blah, I had my projects confused.  This isn't Rust and we don't use clap here.

**Comment by bgilbert** [comment]
Thanks for reporting this.  Fix in https://github.com/coreos/butane/pull/268.
