### ISSUE TITLE
Incorrect encoding format in Windows

### ISSUE THREAD

**Issue by imjimmeh** [coreos/butane#293]
Not sure if it's me doing something very stupid (very likely), but this has caused me far longer to diagnose than it should have:
-Input encoding format is UTF-8 (with Windows linebreaks)

-Output encoding format is UTF-16 (I forgot which exact version)

Apparently the config needs to be ANSI (not sure if this is supposed to be obvious, or if it's stated anywhere, but either way I hadn't realised), so by default the created/converted file will cause errors upon the CoreOS starting.

**Comment by bgilbert** [comment]
Are you saying that Butane is producing UTF-16 output on Windows?  That would be a bug, as everything should be UTF-8: the YAML input, the JSON output, and the config received by Ignition.  Please post the exact command you're using to invoke Butane, the error reported by Ignition, and any other details you think might be helpful.

**Comment by imjimmeh** [comment]
Indeed - it is producing UTF-16 in Windows (for me at least).

Exact command is "butane.exe --strict -r ignition.yaml > example9.ign" (good file naming I know). I did have the pretty argument (--pretty?) at one point, which had no change.

I can't remember the exact error reported by ignition, but it was when trying to run the /usr/lib/ignition/user.ign - it complained about an invalid character at line 1,2 (ÿ) and failed to parse it.

My .yaml file was pretty spase at the time, as an example I can replicate it with the following .yaml:
`variant: fcos
version: 1.4.0
passwd:
  users:
    - name: core
      ssh_authorized_keys:
        - ssh-rsa NOTAREALKEY`

In Powershell with command:
F:\butane.exe --strict -r ignitionfake.yaml > examplefake.ign

Produces (as expected) the following .ign output:
`{"ignition":{"version":"3.3.0"},"passwd":{"users":[{"name":"core","sshAuthorizedKeys":["ssh-rsa NOTAREALKEY"]}]}}`

However, the encoding (according to Notepad++, and without testing again I would bet this would error again) is "UTF-16 LE BOM".

Version of butane.exe 0.13.1 according to --version.

**Comment by imjimmeh** [comment]
Ah ignore me I'm an idiot - just realised the > filename would cause powershell to write the file. 

Using the correct argument (i.e. -o filename) produces UTF-8.

Apologies!
