### ISSUE TITLE
openshift/v4_13_exp: revise extensions feature before stabilizing the API

### ISSUE THREAD

**Issue by jmarrero** [coreos/butane#314]
The extensions API added on: https://github.com/coreos/butane/pull/304 which is part of https://github.com/coreos/butane/issues/300 needs to be revisited and discussed before stabilizing the 1.5 API. This feature might conflict with the MCO extensions capabilities and needs to be further examined before it's considered stable.

Further more @bgilbert has raised https://github.com/coreos/butane/issues/312 which might block this from being used on Openshift.
More context on: https://github.com/coreos/butane/pull/304#discussion_r790336682 & https://github.com/coreos/butane/pull/304#discussion_r791004773

**Comment by bgilbert** [comment]
I think it's okay to stabilize `fcos` 1.5.0 without this; the concern is stabilizing it into an `openshift` spec.

**Comment by bgilbert** [comment]
We're getting close to stabilizing a 1.5.0 spec.  The functionality wouldn't be available in `openshift` 4.13.0 but would be available in 4.14.0.  @jmarrero, @jlebon, how do you feel about the state of this feature?

**Comment by jmarrero** [comment]
I am torn... while the declarative interface of butane makes sense in our current world. I am not sure that with the discussions we are having about layering we want to expose this functionality to openshift just yet. Might be worth adding it to our discussions on layering/bootc/ignition future.

**Comment by travier** [comment]
Agree that we should remove that from the about to be stabilized spec and defer it for the next one.

**Comment by bgilbert** [comment]
@jlebon, @jmarrero, @travier, and I discussed this OOB and agreed that we should back out the `extensions` sugar for now.  It seems like a pretty narrow UX, and may not be a good fit for the layering use cases generally.  @cgwalters, any objection?

**Comment by cgwalters** [comment]
Makes sense to me.
