### ISSUE TITLE
arm64 build and container

### ISSUE THREAD

**Issue by stobbsm** [coreos/butane#324]
### Feature Request: arm64 build

I know it's quite simple to do myself with go, but I've started using an arm64 system (MacBook m1 air) as my main laptop. I've built, tested, and used it for arm64, but was wondering if there was interest in having an arm64 build and container generated?

If so, I can have a PR made shortly to make it happen.

**EDIT** It may be better to just set env variables per run, instead of embedding them into the scripts. Using docker build-args would simplify the maintenance and the ci process

**Comment by bgilbert** [comment]
There is interest, yes.  My understanding is that we'd need to switch from building in Quay to building elsewhere (perhaps in GitHub Actions) and pushing to Quay.  Actually, that might be a good cleanup anyway; GitHub Actions gives us better visibility than Quay does.

**Comment by stobbsm** [comment]
TBH, I've never used quay for building. This will still end up using the x86_64 container to build it, just cross compiles the go.

Since it's using the scratch container, I think it'll only need the appropriate tags to distinguish it from x86_64 platform

**Comment by stobbsm** [comment]
I've gotten it working with docker buildx. It will build both containers at the same time for both platforms.

Now, I'll need to figure it out for Podman, which is a little harder to do.

**Comment by stobbsm** [comment]
started work here #325
