### ISSUE TITLE
Automatically-compressed resources interact badly with config merging

### ISSUE THREAD

**Issue by cgwalters** [coreos/butane#332]
I'm working on updating the MCO to use the latest butane instead of fcct in https://github.com/openshift/machine-config-operator/pull/2976

There were a few minor bugs on the MCO side this unveiled, but this one looks like a clear Ignition bug.  Basically in the MCO we heavily do config merging.

Butane now uses compression by default (which is fine; but I had to fix up various places in the MCO to correctly handle this).  But, Ignition's native config merging seems to incorrectly carry the compression flag forward from old files when trying to override with an uncompressed file:

```
diff --git a/pkg/controller/common/helpers_test.go b/pkg/controller/common/helpers_test.go
index 8934b7d98..c667bbc33 100644
--- a/pkg/controller/common/helpers_test.go
+++ b/pkg/controller/common/helpers_test.go
@@ -7,6 +7,7 @@ import (
 
 	"github.com/clarketm/json"
 	ign2types "github.com/coreos/ignition/config/v2_2/types"
+	ign3 "github.com/coreos/ignition/v2/config/v3_2"
 	ign3types "github.com/coreos/ignition/v2/config/v3_2/types"
 	validate3 "github.com/coreos/ignition/v2/config/validate"
 	"github.com/stretchr/testify/assert"
@@ -135,6 +136,30 @@ func TestValidateIgnition(t *testing.T) {
 	require.NotNil(t, isValid3)
 }
 
+func TestIgnitionMergeCompressed(t *testing.T) {
+	testIgn3Config := ign3types.Config{}
+	testIgn3Config.Ignition.Version = "3.2.0"
+	mode := 420
+	testfiledata := "data:;base64,H4sIAAAAAAAAA0vLz+cCAKhlMn4EAAAA"
+	compression := "gzip"
+	tempFile := ign3types.File{Node: ign3types.Node{Path: "/etc/testfileconfig"},
+		FileEmbedded1: ign3types.FileEmbedded1{Contents: ign3types.Resource{Source: &testfiledata, Compression: &compression}, Mode: &mode}}
+	testIgn3Config.Storage.Files = append(testIgn3Config.Storage.Files, tempFile)
+
+	testIgn3Config2 := ign3types.Config{}
+	testIgn3Config2.Ignition.Version = "3.2.0"
+	testfiledata = "data:hello world"
+	tempFile = ign3types.File{Node: ign3types.Node{Path: "/etc/testfileconfig"},
+		FileEmbedded1: ign3types.FileEmbedded1{Contents: ign3types.Resource{Source: &testfiledata}, Mode: &mode}}
+	testIgn3Config2.Storage.Files = append(testIgn3Config2.Storage.Files, tempFile)
+
+	merged := ign3.Merge(testIgn3Config, testIgn3Config2)
+	assert.NotNil(t, merged)
+	mergedFile := merged.Storage.Files[0]
+	assert.Equal(t, "data:hello world", *mergedFile.Contents.Source)
+	assert.Equal(t, nil, mergedFile.Contents.Compression)
+}
+
 func TestConvertIgnition2to3(t *testing.T) {
 	// Make a new Ign spec v2 config
 	testIgn2Config := ign2types.Config{}
```

**Comment by cgwalters** [comment]
> Config merging is [defined](https://coreos.github.io/ignition/operator-notes/#child-configs-take-precedence-when-specified) to be field-by-field.

OK but...a few things going on here.  First, in the MCO all the internals today are oriented around Ignition merging, not butane merging.  I don't think we can really change that *unless* we had code that converted Ignition to butane.  ([here's a free project name](https://en.wikipedia.org/wiki/Maxwell%27s_demon) for that).

>  but it's also possible that a child source intends to override a parent source and inherit the latter's compression.

I'm dubious.  In what scenarios would the child source not be written by something that knows the compression type?  

> Or, we could solve the problem categorically by disabling automatic compression for any config that has child configs. 

Wouldn't work for the MCO case, we are generating ignition configs from butane, then merging those configs with later with other configs via the `Merge` API in Go code.

I think the canonical fix here is to ensure that anywhere we're generating a file, *also* set the compression field (usually to `""` because all this code predates Ignition compression).

Or alternatively, walk over the config just before merging and apply that.

**Comment by cgwalters** [comment]
Another alternative is Ignition could gain a `merge2` behavior that is *defined* to handle `compression` in a not-surprising way.  Maybe best done by waiting a bit, seeing if any other config merging surprises are discovered, and roll those in too/2.

**Comment by cgwalters** [comment]
> For uncompressed inline and local resources, I think it's pretty clear that Butane should emit "compression": "". It knows whether it has compressed the contents, so it needs to override any parent field saying otherwise. 

OK yes though, this would fix things for us I think.

**Comment by bgilbert** [comment]
Yup, for `inline` and `local` resources.

**Comment by bgilbert** [comment]
Fix in https://github.com/coreos/butane/pull/341.

**Comment by cgwalters** [comment]
OK I think to say it simply, everything generating Ignition should be setting the compression field.  I think what would help here is an opinionated API for this like https://github.com/openshift/machine-config-operator/blob/a0fd73657a571bdbf75e19d06ab0371e2de5638b/test/helpers/helpers.go#L155 but part of Ignition or so?

**Comment by cgwalters** [comment]
https://github.com/openshift/machine-config-operator/pull/3128

**Comment by bgilbert** [comment]
> OK I think to say it simply, everything generating Ignition should be setting the compression field.

The requirement to clear the `compression` field only applies to child configs that are overriding possibly-compressed contents of a resource in a parent config.  In general, child configs already need to know when they're doing that.  (The parent config was writing e.g. a config file that implemented certain semantics, and clobbering that file will have semantic consequences that the child will need to account for, e.g. by copying some parts of the file from the parent config.)  It should be sufficient to set the compression field only when overriding a parent resource in this way.

The MCO might plausibly choose to set `compression: ""` everywhere for convenience.  If it doesn't know what it's overriding, though, I wonder if there are latent bugs where files from one Ignition fragment are being clobbered by a different Ignition fragment without anyone noticing.
