### ISSUE TITLE
Providing winget package manifest for butane

### ISSUE THREAD

**Issue by Okeanos** [coreos/butane#384]
In the same vain that I added butane to e.g. [Homebrew](https://formulae.brew.sh/formula/butane) and [scoop](https://scoop.sh/#/apps?q=butane&s=0&d=1&o=true) I would like to contribute a butane manifest to [winget](https://github.com/microsoft/winget-cli) ([winget-packages](https://github.com/microsoft/winget-pkgs)) now that it supports portable packages.

However, before doing so I would like to make sure to prevent the "scoop debacle" some of you may remember (see [ScoopInstaller/Extras/pull/6554](https://github.com/ScoopInstaller/Extras/pull/6554)) by ensuring the PR and its details are up to _your_ standards first. Specifically, the winget package manifests allow a very wide range of attributes to be (optionally) included.

Some examples of attributes you may want to have specified in a specific pattern that are not immediately obvious for an external contributor:

- `PackageIdentifier` (fully qualified name including a publisher-like identifier and any subdivision/group identifier)
- `Publisher`
- `PublisherUrl`
- `PublisherSupportUrl`
- …

A full list of attributes (for reference purposes) for the current version of manifests are:

- https://aka.ms/winget-manifest.installer.1.2.0.schema.json 
- https://aka.ms/winget-manifest.defaultLocale.1.2.0.schema.json 
- https://aka.ms/winget-manifest.version.1.2.0.schema.json 

My current WIP draft with a **minimal** set of required attributes can be seen [here](https://github.com/microsoft/winget-pkgs/compare/master...Okeanos:winget-pkgs:butane-0.15.0). Please note that someone already added some software within the `Fedora` namespace which I decided to reuse but subdivide into `CoreOS`.

A more complete/complex example showcasing some of the attributes I mentioned above would be the [kubectl PR](https://github.com/microsoft/winget-pkgs/pull/69105/files).

I would be willing to make the occasional winget-pkg PR and keep the packages up to date with butane releases for the foreseeable future to prevent unnecessary maintenance overhead for you. I would also make the necessary changes to the CoreOS docs, of course.

**Comment by bgilbert** [comment]
I mean, the 'scoop debacle' wasn't on you.  The language that was corrected in 6554 had been specifically demanded by downstream over your objections.

I haven't studied this closely, but on a quick skim, the minimal manifest looks okay.  Would you be willing to add any additional attributes you think make sense, and then ping this issue again?

**Comment by Okeanos** [comment]
In that case I'll add a couple of semi-obvious ones that are also specified for kubectl:

- `PublisherSupportUrl: https://github.com/coreos/butane/issues`
- `PackageUrl: https://coreos.github.io/butane/`
- `LicenseUrl: https://github.com/coreos/butane/blob/main/LICENSE`
- `Moniker: butane`

Anything beyond that is probably just too much overhead to keep in sync.

**Comment by lucab** [comment]
Closed by https://github.com/microsoft/winget-pkgs/pull/77943.
Docs at https://github.com/coreos/fedora-coreos-docs/pull/453.
Thanks a lot @Okeanos! :blue_heart:
