### ISSUE TITLE
RFE: new variant supporting RHEL for Edge

### ISSUE THREAD

**Issue by miabbott** [coreos/butane#396]
Creating this issue as a place-holder for discussing a variant specific to the RHEL for Edge use case.

We envision supporting Ignition on RHEL for Edge systems in the future for handling simple configuration tasks like writing files and enabling systemd units.  We don't want to (immediately) support the full complement of Ignition features (i.e. disks, RAID, filesystems, LUKS) so it was suggested a new variant be created in butane to denylist the features we don't want to support.

cc: @runcom

**Comment by bgilbert** [comment]
By way of example, the `openshift` variant [also denylists Ignition features](https://github.com/coreos/butane/blob/c18326b410d5188fa8bd214e7cf341caf57ad4c6/config/openshift/v4_12/translate.go#L174-L279).

Is the intent to avoid supporting the partitioning/filesystem features for data partitions as well?  One possible middle ground is to support them for data partitions but not boot partitions.

**Comment by runcom** [comment]
> Is the intent to avoid supporting the partitioning/filesystem features for data partitions as well? One possible middle ground is to support them for data partitions but not boot partitions.

in general anything related to partitioning/layout/luks/boot would be taken out at first - we do that in Image Builder basically

**Comment by bgilbert** [comment]
Is there no circumstance in which a user might want to, for example, create filesystems on a second disk during provisioning?

**Comment by ashcrow** [comment]
COS-1879

**Comment by control-d** [comment]
> > Is the intent to avoid supporting the partitioning/filesystem features for data partitions as well? One possible middle ground is to support them for data partitions but not boot partitions.
> 
> in general anything related to partitioning/layout/luks/boot would be taken out at first - we do that in Image Builder basically

@runcom, can you help me understand how Image Builder handles filesystems and partitions? I was under the impression that it can only generate the root filesystem contents. Is it able to configure disk/partition/filesystem layout, or is it that we only want to support the default layout and not other configurations?

**Comment by runcom** [comment]
@control-d default configuration still - we have use cases for custom partition schemes but we’re not there yet and we didn’t want to expose something as of yet
