### ISSUE TITLE
Bump `ignition` experimental to 3.6.0-experimental

### ISSUE THREAD

**Issue by travier** [coreos/butane#558]
# Bumping spec versions

This checklist describes bumping the Ignition spec version, `base` version, and distro versions. If your scenario is different, modify to taste.

## Stabilize Ignition spec version

- [x] Bump `go.mod` for new Ignition release and update vendor.
- [x] Update imports. Drop `-experimental` from Ignition spec versions in `*/translate_test.go`.

## Bump base version

- [x] Rename `base/vB_exp` to `base/vB` and update `package` statements. Update imports.
- [x] Copy `base/vB` to `base/vB+1_exp`.
- [x] Update `package` statements in `base/vB+1_exp`.

## Bump distro version

- [x] Rename `config/distro/vD_exp` to `config/distro/vD` and update `package` statements. Update imports.
- [x] Drop `-experimental` from `init()` in `config/config.go`.
- [x] Drop `-experimental` from examples in `docs/`.
- [x] Copy `config/distro/vD` to `config/distro/vD+1_exp`.
- [x] Update `package` statements in `config/distro/vD+1_exp`. Bump its base dependency to `base/vB+1_exp`.
- [x] Import `config/vD+1_exp` in `config/config.go` and add `distro` `C+1-experimental` to `init()`.

## Bump Ignition spec version

- [x] Bump Ignition types imports and rename `ToIgnI` and `TestToIgnI` functions in `base/vB+1_exp`. Bump Ignition spec versions in `base/vB+1_exp/translate_test.go`.
- [x] Bump Ignition types imports in `config/distro/vD+1_exp`. Update `ToIgnI` function names, `util` calls, and header comments to `ToIgnI+1`.

## Update docs

- [x] Update `internal/doc/main.go` to add the new stable spec and reference the new experimental spec in `generate()`.
- [x] Run `generate` to regenerate spec docs.
- [x] Update `docs/specs.md`.
- [ ] Update `docs/upgrading-*.md` for the new spec version. Copy the relevant section from Ignition's `doc/migrating-configs.md`, convert the configs to Butane configs, convert field names to snake case, and update wording as needed. Add subsections for any new Butane-specific features.
- [x] Note the stabilization in `docs/release-notes.md`, following the format of previous stabilizations. Drop the `-exp` version suffix from any notes for the upcoming release.

**Comment by prestist** [comment]
Closed by #562
