### ISSUE TITLE
add sugar for modifying kernel arguments

### ISSUE THREAD

**Issue by dustymabe** [coreos/butane#57]
For our [cgroup v2 strategy ticket](https://github.com/coreos/fedora-coreos-tracker/issues/292), we identified that we need an easy way for a user to be able to set kernel arguments for many reasons, but also to toggle cgroups v2 on and off.

We need the ability for a user to easily configure kernel arguments and also documentation on how to do that.

**Comment by jdoss** [comment]
Any ETA on when this is going to be considered? Using FCOS with rootless podman with cgroups v1 is very painful.

**Comment by lucab** [comment]
No ETA that I am aware for this at this point, but I don't expect this feature to land anytime soon.

As noted in https://github.com/coreos/fedora-coreos-tracker/issues/292#issuecomment-566098314, there is quite a bit of groundwork to be done at initrd/ostree/ignition level.
Once the primitives are in place there, the sugar here should be relatively straightforward to wire.

**Comment by bgilbert** [comment]
This is done in `fcos` spec 1.4.0 and [documented](https://docs.fedoraproject.org/en-US/fedora-coreos/kernel-args/) in FCOS.
